[/Script/Engine.GameUserSettings]
; UE 窗口模式枚举：0=独占全屏，1=无边框全屏，2=普通窗口。
bUseDesktopResolutionForFullscreen=False
ResolutionSizeX=1600
ResolutionSizeY=900
LastUserConfirmedResolutionSizeX=1600
LastUserConfirmedResolutionSizeY=900
FullscreenMode=2
LastConfirmedFullscreenMode=2
PreferredFullscreenMode=2
Version=5
